 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/queijos", type: :request do
  # Queijo. As you add validations to Queijo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Queijo.create! valid_attributes
      get queijos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      queijo = Queijo.create! valid_attributes
      get queijo_url(queijo)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_queijo_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      queijo = Queijo.create! valid_attributes
      get edit_queijo_url(queijo)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Queijo" do
        expect {
          post queijos_url, params: { queijo: valid_attributes }
        }.to change(Queijo, :count).by(1)
      end

      it "redirects to the created queijo" do
        post queijos_url, params: { queijo: valid_attributes }
        expect(response).to redirect_to(queijo_url(Queijo.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Queijo" do
        expect {
          post queijos_url, params: { queijo: invalid_attributes }
        }.to change(Queijo, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post queijos_url, params: { queijo: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested queijo" do
        queijo = Queijo.create! valid_attributes
        patch queijo_url(queijo), params: { queijo: new_attributes }
        queijo.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the queijo" do
        queijo = Queijo.create! valid_attributes
        patch queijo_url(queijo), params: { queijo: new_attributes }
        queijo.reload
        expect(response).to redirect_to(queijo_url(queijo))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        queijo = Queijo.create! valid_attributes
        patch queijo_url(queijo), params: { queijo: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested queijo" do
      queijo = Queijo.create! valid_attributes
      expect {
        delete queijo_url(queijo)
      }.to change(Queijo, :count).by(-1)
    end

    it "redirects to the queijos list" do
      queijo = Queijo.create! valid_attributes
      delete queijo_url(queijo)
      expect(response).to redirect_to(queijos_url)
    end
  end
end
